### ISSUE TITLE
Could I see a demo video or screenshots

### ISSUE THREAD

**Issue by kenyroj** [xielong/chatgpt-code-review-gerrit-plugin#3]
Hi

I would like to integrated this plugin to our gerrit system for code optimization. I want to see the result of this plugin.

1. Any screenshot or video for this plugin?
2. Suggested environment? Like version of gerrit.

Thanks

**Comment by xielong** [comment]
Hi,

Thank you for your interest in integrating the plugin into your Gerrit system for code optimization.

Unfortunately, our business code contains sensitive information, so we aren't able to provide screenshots or videos of the plugin in action. However, I can share that our development environment uses Java 11 and Maven 3, and the Gerrit version we are working with is 3.8.
